version: '20.1'

services:
  postgresdb:
    image: bitnami/postgresql:latest
    env_file: "build.env"
    volumes:
      - ./sql/data:/bitnami/postgresql
    ports: 
      - '5432:5432'
      - '34567:5432'
    networks:
      - epiphyte-corp-dot-net
    healthcheck:
      test: pg_isready -U postgres -d epiphyte
      interval: 3s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    env_file: "build.env"
    networks:
      - epiphyte-corp-dot-net
    volumes:
      - ./sql/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:your_password@postgresdb/epiphyte?sslmode=disable", "up" ]
    links: 
      - postgresdb
    depends_on:
      postgresdb:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: always
    env_file: "build.env"

    # overwrite the env values from build.env file
    # the 'environment' properties has higher priority
    environment:
      - SERVER_LISTENER=0.0.0.0:3000
      - POSTGRESQL_HOST=postgresdb:5432
      - GIN_MODE=release
    ports:
      - '3000:3000'
    networks:
      - epiphyte-corp-dot-net
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - ./docker_log:/log

  scheduler:
    build:
      context: .
      dockerfile: scheduler.Dockerfile
    restart: always

    # NOTE: set the scheduling here
    environment:
      - SCHEDULER_REFRESH_URL=http://api:3000/api/v1/indego-data-fetch-and-store-it-db
      - SCHEDULER_REFRESH_INTERVAL=1h
      # - SCHEDULER_REFRESH_INTERVAL=3m
    networks:
      - epiphyte-corp-dot-net
    depends_on:
      - postgresdb
      - api
    volumes:
      - ./docker_log:/log

networks:
  epiphyte-corp-dot-net:
